#!/usr/bin/env node
const program = require("commander");
const packageJson = require("./package.json");
const path = require("path");
const generateClasses = require("./src/cli");

program
    .version(packageJson.version)
    .arguments("[jsonPath]")
    .option("-d, --default [defaultValue]", "Override default undefined value")
    .option("--private [privateSuffix]", "Override default undefined value")
    .action((jsonPath, options) => {
        generateClasses(path.resolve(jsonPath), options);
    })
    .parse(process.argv);
